# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
   name: Linux

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '*.tgz' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy npm package'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'package.json' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy package.json'   

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/npm'
    artifactName: npm
  displayName: 'Publish npm artifact'

-stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: main
    pool:
      name: Linux
      demands:
       - agent.name -equals Linux
    strategy:
      runOnce:
        deploy:
          steps:           
          - task: AzureRmWebAppDeployment@4
            inputs:
             ConnectionType: 'AzureRM'
             azureSubscription: 'sp'
             appType: 'webAppLinux'
             WebAppName: 'POCAppservice'
             packageForLinux: '$(Build.ArtifactStagingDirectory)/npm/'
- task: WhiteSource@21
  inputs:
    cwd: '$(Build.ArtifactStagingDirectory)'
    projectName: 'poc'

